Supply the required AdministratorAccountId param
My last build failed with:

Error: error creating CloudFormation Stack
(AWSCloudFormationStackSetExecutionRole): ValidationError: Parameters:
[AdministratorAccountId] must have values status code: 400, request id:
6cf0c851-fcdd-4b51-b4dd-3583648a2a13
with aws_cloudformation_stack.AWSCloudFormationStackSetExecutionRole
on stacks.tf line 7, in resource "aws_cloudformation_stack"
"AWSCloudFormationStackSetExecutionRole":
resource "aws_cloudformation_stack"
"AWSCloudFormationStackSetExecutionRole" {